name = "message-server"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "GAME_SESSIONS"
class_name = "GameSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameSession"]
